---
- name: pip install neutron
  command: pip install -i {{ openstack.pypi_mirror }} /opt/stack/neutron
  register: result
  until: result|success
  retries: 3
  delay: 60

- name: neutron rootwrap
  command: rsync -avh /opt/stack/neutron/etc/neutron/rootwrap.d /etc/neutron

- name: restart neutron services
  restart_if_running: service={{ item }}
#  with_items:
#    - neutron-server
#    - neutron-dhcp-agent
#    - neutron-l3-agent
#    - neutron-lbaas-agent
#    - neutron-openvswitch-agent
